# Generated by Django 2.2.16 on 2022-05-07 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='score',
            field=models.PositiveSmallIntegerField(default=1, help_text='Введите оценку от 1 до 10', validators=[django.core.validators.MaxValueValidator(10, message='Оценка должна быть <= 10'), django.core.validators.MinValueValidator(1, message='Оценка должна быть >= 1')], verbose_name='Оценка'),
        ),
    ]
